apiVersion: v2
kind: Pod
metadata:
  name: servicepod
  namespace: roboshop
  labels: 
    app: nginx
    demo: krishna

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
###########
apiVersion: v2
kind: Service
metadata:
  name: nginx-service
  namespace: roboshop
  
spec:
  selector:
    app: nginx
    demo: krishna

  ports:
    protocal: tcp
    port: 80
    targetPort: 80




