apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod       # Changed to conform to lowercase and DNS-1123 standards
  namespace: roboshop
  labels:
    trainer: krishna
    demo: nodeport

spec:
  containers:
  - name: nodeport         # Changed to lowercase to meet RFC 1123 standards
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service   # Changed to lowercase to meet DNS-1035 standards
  namespace: roboshop

spec:
  type: NodePort
  selector:
    trainer: krishna
    demo: nodeport

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80