apiVersion: v1
kind: Pod
metadata:
  name: nodeportPod
  namespace: roboshop
  labels:
    trainer: krishna
    demo: nodeport

spec:
  containers:
  - name: nodePort
    image: nginx
    ports:
    - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: ServiceNodeport

spec:
  type: NodePort
  selector:
    trainer: krishna
    demo: nodeport

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80