apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod       
  namespace: roboshop
  labels:
    trainer: krishna
    demo: nodeport

spec:
  containers:
  - name: nodeport        
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service   
  namespace: roboshop

spec:
  type: NodePort
  selector:
    trainer: krishna
    demo: nodeport

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80