apiVersion: v1
kind: Pod
metadata:
  name: loadbalancerpod
  namespace: roboshop
  labels:
    name: krishnareddy
    demo: loadbalancer

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-pod
  namespace: roboshop

spec:
  type: loadbalancer
  selector:
    name: krishnareddy
    demo: loadbalancer
  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80