apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer-pod       
  namespace: roboshop
  labels:
    app: nginx            
    demo: loadbalancer

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: roboshop

spec:
  type: LoadBalancer            
  selector:                     
    app: nginx
    demo: loadbalancer

  ports:
  - protocol: TCP               
    port: 80                    
    targetPort: 80              