apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: roboshop
  labels:
    app: krishna
    demo: devops

spec:
  replicas: 4
  selector:
    matchLabels:
      app: krishna
      demo: devops

  template:
    metadata:
      labels:
        app: krishna
        demo: devops
    spec:
      containers:
      - name: nginx
        image: nginx
        args:                   # Adding runtime flags
        - --flag1=value1
        - --flag2=value2
        env:                    # Adding environment variables as flags
        - name: ENV_FLAG1
          value: "example-value1"
        - name: ENV_FLAG2
          value: "example-value2"
        ports:
        - containerPort: 80