apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: roboshop
  labels:
    app: krishna
    demo: devops

spec:
  replicas: 4
  selector:
    matchLabels:
      app: krishna
      demo: devops

  template:
    metadata:
      labels:
        app: krishna
        demo: devops
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-perl
        ports:
        - containerPort: 80