apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: roboshop
  labels:
    app: nginx
    tier: frontend

spec:
  replicas: 3 #it means three replicas we want
  selctor:  # replica-set labels
    matchLabels:
      app: nginx
      tier: frontend
  
  templates:   #it is pod defination, it dont have apiVersion: and kind: , the reason pod is subset of the replicaset.
    metadata:
      namespace: roboshop
      labels:
        app: nginx
        tier: frontend

  spec:
    containers:
    - name: nginx
      image: nginx
