apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    
    - name: almalinux
      image: almalinux:8
      command: ["sh", "-c", "echo 'hello, kubernetes!'; sleep 3600"]
     

