apiVersion: v1
kind: Pod
metadata:
  name: envpod
  namespace: roboshop
  labels:
    Trainer: "krishnaReddy"
    duration: "120HOURS"
  annotations:
    com.roboshop.training: "120hours"
    jenkins.uls: "krishna.com/roboshop"

spec:
  containers:
  - name: env
    image: nginx
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"